name: Install μpkg dependencies
description: Read upkg.json and installs the dependencies without using μpkg

inputs:
  working-directory:
    description: μpkg project root
    default: '.'

runs:
  using: composite
  steps:
  - name: Install dependencies
    run: |
      sha256=$(jq -r '.dependencies[0].sha256' upkg.json)
      mkdir -p .upkg/.packages/docopt-lib.sh@$sha256
      wget -qO- "$(jq -r '.dependencies[0].tar' upkg.json)" | \
        tar -xzC .upkg/.packages/docopt-lib.sh@$sha256
      ln -s .packages/docopt-lib.sh@$sha256 .upkg/docopt-lib.sh
    shell: bash
    working-directory: ${{ inputs.working-directory }}
