name: Create μpkg bundle

on:
  workflow_call: {}

jobs:
  create-bundle:
    name: Create upkg.tar.gz
    runs-on: ubuntu-latest
    steps:
    - id: program_version
      uses: orbit-online/program-version@v1.0.0
    - uses: actions/checkout@v4
      with:
        path: upkg
    - name: Create μpkg bundle
      run: upkg bundle -d ../upkg.tar.gz -V "${{ steps.program_version.outputs.version }}"
      working-directory: upkg
    - name: Upload upkg.tar.gz
      uses: actions/upload-artifact@v4
      with:
        name: upkg.tar.gz
        path: upkg.tar.gz
        retention-days: 1
