name: Check shasum

on:
  push:
    branches: [ '*' ]
    paths: [ 'upkg.sh', 'README.md', '.github/workflows/check-shasum.yaml' ]
  pull_request:
    branches: [ '*' ]
    paths: [ 'upkg.sh', 'README.md', '.github/workflows/check-shasum.yaml' ]

jobs:
  lint:
    name: Check shasum
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check if the shasum from the README.md matches the shasum of upkg.sh
      run: |
        printf '%s  upkg.sh\n' "$(grep 'shasum -a 256' README.md | sed 's/^.*\([a-f0-9]\{64\}\).*$/\1/')" | shasum -a 256 -c -
