name: Check shasum

on:
  push:
    branches: ['*']
    tags: ['!v*']

jobs:
  check-install-snippet:
    name: Check shasum
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Ensure that the shasum and release URL in the README match
      run: |
        url=$(grep -Eom1 'u=https://github\.com/orbit-online/upkg/releases/download/[^/]+/upkg-install\.tar\.gz' README.md)
        sha256=$(grep -Eom1 'c=[0-9a-f]{64}' README.md)
        wget --server-response -qO>(shasum -a 256 -c <(echo "${sha256#c=}  -")) "${url#u=}"
