name: Create μpkg install snapshot

on:
  workflow_call: {}

jobs:
  create-bundle:
    uses: ./.github/workflows/create-bundle.yaml
    secrets: inherit
  create-install-snapshot:
    needs: [create-bundle]
    name: Create upkg-install.tar.gz
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        path: upkg
    - name: Download μpkg bundle
      uses: actions/download-artifact@v4
      with:
        name: upkg.tar.gz
    - name: Create install snapshot
      run: upkg/tools/create-install-snapshot.sh upkg.tar.gz upkg-install.tar.gz
    - name: Upload upkg-install.tar.gz
      uses: actions/upload-artifact@v4
      with:
        name: upkg-install.tar.gz
        path: upkg-install.tar.gz
        retention-days: 1
