name: Create μpkg-compat bundle & install snapshot

on:
  workflow_call: {}

jobs:
  create-bundle:
    uses: ./.github/workflows/create-bundle.yaml
    secrets: inherit
  create-compat-install-snapshot:
    needs: [create-bundle]
    name: Create upkg-compat-install.tar.gz
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        path: upkg
    - name: Download μpkg bundle
      uses: actions/download-artifact@v4
      with:
        name: upkg.tar.gz
    - name: Create compat-install snapshot
      run: upkg/tools/create-install-snapshot.sh upkg.tar.gz upkg-compat.tar.gz upkg-compat-install.tar.gz
    - name: Upload upkg-compat.tar.gz
      uses: actions/upload-artifact@v4
      with:
        name: upkg-compat.tar.gz
        path: upkg-compat.tar.gz
        retention-days: 1
    - name: Upload upkg-compat-install.tar.gz
      uses: actions/upload-artifact@v4
      with:
        name: upkg-compat-install.tar.gz
        path: upkg-compat-install.tar.gz
        retention-days: 1
