name: Bundle as install package

on:
  push:
    branches: ['*']
    tags: ['!v*']
  workflow_call: {}

jobs:
  upkg-bundle:
    uses: ./.github/workflows/upkg-bundle.yaml
    secrets: inherit
  install-bundle:
    needs: [upkg-bundle]
    name: Create upkg-install.tar.gz
    runs-on: ubuntu-latest
    steps:
    - name: Download Î¼pkg bundle
      uses: actions/download-artifact@v4
      with:
        name: upkg.tar.gz
    - name: Create install package
      run: |
        sha256=$(shasum -a 256 upkg.tar.gz | cut -d ' ' -f1)
        mkdir -p install/bin install/lib/upkg/.upkg/.packages/upkg.tar@$sha256 install/lib/upkg/.upkg/.bin
        tar -xzC install/lib/upkg/.upkg/.packages/upkg.tar@$sha256 -f upkg.tar.gz
        ln -sT .packages/upkg.tar@$sha256 install/lib/upkg/.upkg/upkg
        ln -sT ../lib/upkg/.upkg/.bin/upkg install/bin/upkg
        version=$(jq -r .version install/lib/upkg/.upkg/upkg/upkg.json)
        jq --arg sha256 $sha256 --arg version "$version" '.dependencies=[{
          "tar": "https://github.com/orbit-online/upkg/releases/download/$version/upkg.tar.gz",
          "sha256": $sha256
        }]' <<<'{}'
    - name: Create upkg-install.tar.gz
      run: tar -czC install -f upkg-install.tar.gz bin lib
    - name: Upload upkg-install.tar.gz
      uses: actions/upload-artifact@v4
      with:
        name: upkg-install.tar.gz
        path: upkg-install.tar.gz
        retention-days: 1
