name: Release

on:
  push:
    tags: ['v*']

jobs:
  test:
    uses: ./.github/workflows/test.yaml
    secrets: inherit
  bundle:
    uses: ./.github/workflows/bundle.yaml
    secrets: inherit
  upload-schema:
    needs: [test]
    uses: ./.github/workflows/upload-schema.yaml
    secrets: inherit
  release:
    needs: [test, bundle]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    name: Create GitHub release
    environment: release
    steps:
    - id: program_version
      uses: orbit-online/program-version@v1.0.0
    - uses: actions/checkout@v4
      with:
        ref: ${{ steps.program_version.outputs.version }}
    - name: Get release notes from tag
      id: tag-message
      run: |
        eof="$(openssl rand -hex 8)"
        msg=$(git tag -l --format='%(contents)' "${{ steps.version.outputs.tag }}")
        msg=${msg%%'-----BEGIN'*}
        printf "message<<%s\n%s\n%s\n" "$eof" "$msg" "$eof" >> $GITHUB_OUTPUT
      env:
        REF: ${{ github.ref }}
    - name: Download upkg.tar.gz
      uses: actions/download-artifact@v4
      with:
        name: upkg.tar.gz
    - name: Download upkg.tar.gz
      uses: actions/download-artifact@v4
      with:
        name: upkg-compat.tar.gz
    - name: Download upkg-compat.tar.gz
      uses: actions/download-artifact@v4
      with:
        name: upkg-compat.tar.gz
    - name: Download upkg-install.tar.gz
      uses: actions/download-artifact@v4
      with:
        name: upkg-install.tar.gz
    - name: Download upkg-compat-install.tar.gz
      uses: actions/download-artifact@v4
      with:
        name: upkg-compat-install.tar.gz
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        name: ${{ steps.program_version.outputs.version }}
        body: ${{ steps.tag-message.outputs.message }}
        draft: false
        prerelease: false
        artifacts: upkg.tar.gz,upkg-compat.tar.gz,upkg-install.tar.gz,upkg-compat-install.tar.gz,upkg.schema.json
        artifactErrorsFailBuild: true
        artifactContentType: application/gzip
