name: Test

on:
  push:
    branches: [ '*' ]
    tags: [ 'v*' ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      env:
        SHELLCHECK_OPTS: -x
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: bats-core/bats-action@2.0.0
      with:
        detik-install: false
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run tests
      run: bats tests
      env:
        BATS_LIB_PATH: /usr/lib
