name: Test

on:
  push:
    branches: [ '*' ]
    tags: [ 'v*' ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      env:
        SHELLCHECK_OPTS: -x
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install bats
      uses: bats-core/bats-action@2.0.0
      with:
        support-path: ${{ github.workspace }}/lib/bats-support
        assert-path: ${{ github.workspace }}/lib/bats-assert
        file-path: ${{ github.workspace }}/lib/bats-file
        detik-install: false
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        path: upkg
    - name: Install dependencies
      run: mkdir .upkg; wget -qO.upkg/docopt-lib.sh https://raw.githubusercontent.com/andsens/docopt.sh/0447a7834ecb5120c112456d961f7fdb23e7bdef/docopt-lib.sh
      working-directory: upkg
    - name: Run tests
      run: bats --formatter tap13 --filter-tags '!shellcheck' tests | tee tests/results.tap
      working-directory: upkg
      env:
        BATS_LIB_PATH: ${{ github.workspace }}/lib
        TMPDIR: ${{ github.workspace }}/upkg/tests/bats-tmp
    - name: Generate test summary
      uses: test-summary/action@v2
      with:
        paths: upkg/tests/results.tap
        show: "fail, skip"
      if: always()
