name: Test

on:
  push:
    branches: ['*']
    tags: ['!v*']
  workflow_call: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      env:
        SHELLCHECK_OPTS: -x
      with:
        ignore_paths: >-
          .upkg
          compat/.upkg
  test-bash-versions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bash-version:
        - '4.4'
        - '5.0'
        - '5.1'
        - '5.1.8'
        - '5.1.12'
        - '5.1.16'
        - '5.2'
        - '5.2.9'
        - '5.2.15'
        - '5.2.21'
    steps:
    - name: Install bats
      uses: bats-core/bats-action@2.0.0
      with:
        support-path: ${{ github.workspace }}/lib/bats-support
        assert-path: ${{ github.workspace }}/lib/bats-assert
        file-path: ${{ github.workspace }}/lib/bats-file
        detik-install: false
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        path: upkg
    - name: Install dependencies
      run: tools/install-deps.sh
      working-directory: upkg
    - name: Cache bash versions
      uses: actions/cache@v4
      env:
        cache-name: bash-version
      with:
        path: upkg/tests/assets/bash-versions/bash-${{ matrix.bash-version }}/bash
        key: ${{ env.cache-name }}-${{ matrix.bash-version }}
    - name: Run tests
      run: bats --formatter tap13 --filter-tags '!shellcheck' --jobs 4 tests | tee tests/results.tap
      working-directory: upkg
      env:
        BATS_LIB_PATH: ${{ github.workspace }}/lib
        TEST_BASH_VERSION: ${{ matrix.bash-version }}
        TMPDIR: ${{ github.workspace }}/upkg/tests/bats-tmp
    - name: Fail when tests are skipped
      run: '! grep -q "not ok" tests/results.tap'
      working-directory: upkg
    - name: Generate test summary
      uses: test-summary/action@v2
      with:
        paths: upkg/tests/results.tap
        show: "fail, skip"
      if: always()
  test-distributions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distribution:
        - ubuntu:22.04
        - ubuntu:24.04
        - debian:bullseye
        - debian:bookworm
        - debian:trixie
        - fedora:41
        - rockylinux:9
        - alpine:3.19
        - alpine:3.20
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        path: upkg
    - name: Install dependencies
      run: tools/install-deps.sh
      working-directory: upkg
    - name: Run tests
      run: tests/run.sh --formatter tap13 --filter-tags '!shellcheck' --jobs 4 tests | tee tests/results.tap
      working-directory: upkg
      env:
        BASEIMG: ${{ matrix.distribution }}
    - name: Fail when tests are skipped
      run: '! grep -q "not ok" tests/results.tap'
      working-directory: upkg
    - name: Generate test summary
      uses: test-summary/action@v2
      with:
        paths: upkg/tests/results.tap
        show: "fail, skip"
      if: always()
