name: Test

on:
  push:
    branches: ['*']
    tags: ['!v*']
  workflow_call: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      env:
        SHELLCHECK_OPTS: -x
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install bats
      uses: bats-core/bats-action@2.0.0
      with:
        support-path: ${{ github.workspace }}/lib/bats-support
        assert-path: ${{ github.workspace }}/lib/bats-assert
        file-path: ${{ github.workspace }}/lib/bats-file
        detik-install: false
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        path: upkg
    - name: Install dependencies
      run: tools/install-deps.sh
      working-directory: upkg
    - name: Run tests
      run: bats --formatter tap13 --filter-tags '!shellcheck' tests | tee tests/results.tap
      working-directory: upkg
      env:
        BATS_LIB_PATH: ${{ github.workspace }}/lib
        TMPDIR: ${{ github.workspace }}/upkg/tests/bats-tmp
    - name: Fail when tests are skipped
      run: '! grep -q "not ok" tests/results.tap'
      working-directory: upkg
    - name: Generate test summary
      uses: test-summary/action@v2
      with:
        paths: upkg/tests/results.tap
        show: "fail, skip"
      if: always()
