name: Test

on:
  push:
    branches: [ '*' ]
    tags: [ 'v*' ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      env:
        SHELLCHECK_OPTS: -x
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install bats
      uses: bats-core/bats-action@2.0.0
      with:
        support-path: ${{ github.workspace }}/lib/bats-support
        assert-path: ${{ github.workspace }}/lib/bats-assert
        file-path: ${{ github.workspace }}/lib/bats-file
        detik-install: false
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        path: upkg
    - name: Check package template permissions
      run: diff --color=always -u --label expected --label actual tests/snapshots/package-templates.files <(cd tests/package-templates; tree -n -p --charset=UTF-8 -a -I .git .)
      working-directory: upkg
    - name: Run tests
      run: bats --formatter tap13 --filter-tags '!shellcheck' tests > tests/results.tap
      working-directory: upkg
      env:
        BATS_LIB_PATH: ${{ github.workspace }}/lib
    - name: Generate test summary
      uses: test-summary/action@v2
      with:
        paths: upkg/tests/results.tap
      if: always()
