name: Upload schema

on:
  push:
    branches: ['*']
    tags: ['!v*']
  workflow_call: {}

jobs:
  upload-schema:
    name: Upload JSON schema
    runs-on: ubuntu-latest
    steps:
    - id: program_version
      uses: orbit-online/program-version@v1.0.0
    - name: Checkout
      uses: actions/checkout@v4
    - name: Upload schema to S3
      uses: docker://amazon/aws-cli:2.4.24
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.SCHEMAS_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SCHEMAS_AWS_SECRET_ACCESS_KEY }}
      with:
        args: s3 cp --region eu-west-1 upkg.schema.json s3://schemas.orbit.dev/upkg/upkg-${{ steps.program_version.outputs.version }}.schema.json
    - name: Invalidate the Cloudfront distribution
      uses: docker://amazon/aws-cli:2.4.24
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.SCHEMAS_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SCHEMAS_AWS_SECRET_ACCESS_KEY }}
      with:
        args: cloudfront create-invalidation --region eu-west-1 --distribution-id ${{ vars.SCHEMAS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/upkg/upkg-${{ steps.program_version.outputs.version }}.schema.json"
